image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"
install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
build: off
test_script:
  - pipenv run py.test tests --cov-report term-missing --cov pypac
  - pipenv run coveralls
after_test:
  - pipenv run python setup.py bdist_wheel
deploy: off
artifacts:
  - path: dist/*
