[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.ruff]
select = ["E", "F"]
fix = true
target-version = "py27"
